export const phrases = [
  'I was on mute',
  '(coughing)',
  'Can you repeat that?',
  '____ can you comment?',
  'Shall we start?',
  'He’s in charge of Sales in the Paris office.',
  'Technical difficulties',
  'I’m sharing my screen, can everyone see it?',
  'Is there anything else to discuss?',
  'I’ll confirm our discussion by email.',
  'I need to step out...',
  'Can you hear me ok?',
  'Could you check your microphone please?.',
  'I can’t hear very well.',
  'Please turn to page 14',
  'I agree to a certain extent.',
  'I like that idea.',
  'I see your point.',
  'Let’s ask everyone their opinion.',
  'Let’s speak again next month.',
  '____ what are your thoughts?',
  'Are there any more comments?',
  'Good morning / afternoon',
  'we only have 30 minutes',
  'Echo noise of feedback',
];
